module.exports = [
  { numeroDepartement: "02", numeroRegion: 32, nom: "Aisne" },
  { numeroDepartement: "01", numeroRegion: 84, nom: "Ain" },
  { numeroDepartement: "03", numeroRegion: 84, nom: "Allier" },
  {
    numeroDepartement: "04",
    numeroRegion: 93,
    nom: "Alpes-de-Haute-Provence",
  },
  {
    numeroDepartement: "05",
    numeroRegion: 93,
    nom: "Hautes-Alpes",
  },
  {
    numeroDepartement: "06",
    numeroRegion: 93,
    nom: "Alpes-Maritimes",
  },
  { numeroDepartement: "07", numeroRegion: 84, nom: "Ardèche" },
  { numeroDepartement: "08", numeroRegion: 44, nom: "Ardennes" },
  { numeroDepartement: "09", numeroRegion: 76, nom: "Ariège" },
  { numeroDepartement: "10", numeroRegion: 44, nom: "Aube" },
  { numeroDepartement: "11", numeroRegion: 76, nom: "Aude" },
  { numeroDepartement: "12", numeroRegion: 76, nom: "Aveyron" },
  {
    numeroDepartement: "13",
    numeroRegion: 93,
    nom: "Bouches-du-Rhône",
  },
  { numeroDepartement: "14", numeroRegion: 28, nom: "Calvados" },
  { numeroDepartement: "15", numeroRegion: 84, nom: "Cantal" },
  { numeroDepartement: "16", numeroRegion: 75, nom: "Charente" },
  {
    numeroDepartement: "17",
    numeroRegion: 75,
    nom: "Charente-Maritime",
  },
  { numeroDepartement: "18", numeroRegion: 24, nom: "Cher" },
  { numeroDepartement: "19", numeroRegion: 75, nom: "Corrèze" },
  { numeroDepartement: "21", numeroRegion: 27, nom: "Côte-d'Or" },
  {
    numeroDepartement: "22",
    numeroRegion: 53,
    nom: "Côtes-d'Armor",
  },
  { numeroDepartement: "23", numeroRegion: 75, nom: "Creuse" },
  { numeroDepartement: "24", numeroRegion: 75, nom: "Dordogne" },
  { numeroDepartement: "25", numeroRegion: 27, nom: "Doubs" },
  { numeroDepartement: "26", numeroRegion: 84, nom: "Drôme" },
  { numeroDepartement: "27", numeroRegion: 28, nom: "Eure" },
  {
    numeroDepartement: "28",
    numeroRegion: 24,
    nom: "Eure-et-Loir",
  },
  { numeroDepartement: "29", numeroRegion: 53, nom: "Finistère" },
  {
    numeroDepartement: "2A",
    numeroRegion: 94,
    nom: "Corse-du-Sud",
  },
  { numeroDepartement: "2B", numeroRegion: 94, nom: "Haute-Corse" },
  { numeroDepartement: "30", numeroRegion: 76, nom: "Gard" },
  {
    numeroDepartement: "31",
    numeroRegion: 76,
    nom: "Haute-Garonne",
  },
  { numeroDepartement: "32", numeroRegion: 76, nom: "Gers" },
  { numeroDepartement: "33", numeroRegion: 75, nom: "Gironde" },
  { numeroDepartement: "34", numeroRegion: 76, nom: "Hérault" },
  {
    numeroDepartement: "35",
    numeroRegion: 53,
    nom: "Ille-et-Vilaine",
  },
  { numeroDepartement: "36", numeroRegion: 24, nom: "Indre" },
  {
    numeroDepartement: "37",
    numeroRegion: 24,
    nom: "Indre-et-Loire",
  },
  { numeroDepartement: "38", numeroRegion: 84, nom: "Isère" },
  { numeroDepartement: "39", numeroRegion: 27, nom: "Jura" },
  { numeroDepartement: "40", numeroRegion: 75, nom: "Landes" },
  {
    numeroDepartement: "41",
    numeroRegion: 24,
    nom: "Loir-et-Cher",
  },
  { numeroDepartement: "42", numeroRegion: 84, nom: "Loire" },
  { numeroDepartement: "43", numeroRegion: 84, nom: "Haute-Loire" },
  {
    numeroDepartement: "44",
    numeroRegion: 52,
    nom: "Loire-Atlantique",
  },
  { numeroDepartement: "45", numeroRegion: 24, nom: "Loiret" },
  { numeroDepartement: "46", numeroRegion: 76, nom: "Lot" },
  {
    numeroDepartement: "47",
    numeroRegion: 75,
    nom: "Lot-et-Garonne",
  },
  { numeroDepartement: "48", numeroRegion: 76, nom: "Lozère" },
  {
    numeroDepartement: "49",
    numeroRegion: 52,
    nom: "Maine-et-Loire",
  },
  { numeroDepartement: "50", numeroRegion: 28, nom: "Manche" },
  { numeroDepartement: "51", numeroRegion: 44, nom: "Marne" },
  { numeroDepartement: "52", numeroRegion: 44, nom: "Haute-Marne" },
  { numeroDepartement: "53", numeroRegion: 52, nom: "Mayenne" },
  {
    numeroDepartement: "54",
    numeroRegion: 44,
    nom: "Meurthe-et-Moselle",
  },
  { numeroDepartement: "55", numeroRegion: 44, nom: "Meuse" },
  { numeroDepartement: "56", numeroRegion: 53, nom: "Morbihan" },
  { numeroDepartement: "57", numeroRegion: 44, nom: "Moselle" },
  { numeroDepartement: "58", numeroRegion: 27, nom: "Nièvre" },
  { numeroDepartement: "59", numeroRegion: 32, nom: "Nord" },
  { numeroDepartement: "60", numeroRegion: 32, nom: "Oise" },
  { numeroDepartement: "61", numeroRegion: 28, nom: "Orne" },
  {
    numeroDepartement: "62",
    numeroRegion: 32,
    nom: "Pas-de-Calais",
  },
  {
    numeroDepartement: "63",
    numeroRegion: 84,
    nom: "Puy-de-Dôme",
  },
  {
    numeroDepartement: "64",
    numeroRegion: 75,
    nom: "Pyrénées-Atlantiques",
  },
  {
    numeroDepartement: "65",
    numeroRegion: 76,
    nom: "Hautes-Pyrénées",
  },
  {
    numeroDepartement: "66",
    numeroRegion: 76,
    nom: "Pyrénées-Orientales",
  },
  { numeroDepartement: "67", numeroRegion: 44, nom: "Bas-Rhin" },
  { numeroDepartement: "68", numeroRegion: 44, nom: "Haut-Rhin" },
  { numeroDepartement: "69", numeroRegion: 84, nom: "Rhône" },
  { numeroDepartement: "70", numeroRegion: 27, nom: "Haute-Saône" },
  {
    numeroDepartement: "71",
    numeroRegion: 27,
    nom: "Saône-et-Loire",
  },
  { numeroDepartement: "72", numeroRegion: 52, nom: "Sarthe" },
  { numeroDepartement: "73", numeroRegion: 84, nom: "Savoie" },
  {
    numeroDepartement: "74",
    numeroRegion: 84,
    nom: "Haute-Savoie",
  },
  { numeroDepartement: "75", numeroRegion: 11, nom: "Paris" },
  {
    numeroDepartement: "76",
    numeroRegion: 28,
    nom: "Seine-Maritime",
  },
  {
    numeroDepartement: "77",
    numeroRegion: 11,
    nom: "Seine-et-Marne",
  },
  { numeroDepartement: "78", numeroRegion: 11, nom: "Yvelines" },
  { numeroDepartement: "79", numeroRegion: 75, nom: "Deux-Sèvres" },
  { numeroDepartement: "80", numeroRegion: 32, nom: "Somme" },
  { numeroDepartement: "81", numeroRegion: 76, nom: "Tarn" },
  {
    numeroDepartement: "82",
    numeroRegion: 76,
    nom: "Tarn-et-Garonne",
  },
  { numeroDepartement: "83", numeroRegion: 93, nom: "Var" },
  { numeroDepartement: "84", numeroRegion: 93, nom: "Vaucluse" },
  { numeroDepartement: "85", numeroRegion: 52, nom: "Vendée" },
  { numeroDepartement: "86", numeroRegion: 75, nom: "Vienne" },
  {
    numeroDepartement: "87",
    numeroRegion: 75,
    nom: "Haute-Vienne",
  },
  { numeroDepartement: "88", numeroRegion: 44, nom: "Vosges" },
  { numeroDepartement: "89", numeroRegion: 27, nom: "Yonne" },
  {
    numeroDepartement: "90",
    numeroRegion: 27,
    nom: "Territoire de Belfort",
  },
  { numeroDepartement: "91", numeroRegion: 11, nom: "Essonne" },
  {
    numeroDepartement: "92",
    numeroRegion: 11,
    nom: "Hauts-de-Seine",
  },
  {
    numeroDepartement: "93",
    numeroRegion: 11,
    nom: "Seine-Saint-Denis",
  },
  {
    numeroDepartement: "94",
    numeroRegion: 11,
    nom: "Val-de-Marne",
  },
  {
    numeroDepartement: "95",
    numeroRegion: 11,
    nom: "Val-d'Oise",
  },
  { numeroDepartement: "971", numeroRegion: 01, nom: "Guadeloupe" },
  { numeroDepartement: "972", numeroRegion: 02, nom: "Martinique" },
  { numeroDepartement: "973", numeroRegion: 03, nom: "Guyane" },
  { numeroDepartement: "974", numeroRegion: 04, nom: "La Réunion" },
  { numeroDepartement: "976", numeroRegion: 06, nom: "Mayotte" },
];
