import { Departement } from "./App";

export const departements: Departement[] = [
  { numeroDepartement: "02", nom: "Aisne" },
  { numeroDepartement: "01", nom: "Ain" },
  { numeroDepartement: "03", nom: "Allier" },
  {
    numeroDepartement: "04",
    nom: "Alpes-de-Haute-Provence",
  },
  {
    numeroDepartement: "05",
    nom: "Hautes-Alpes",
  },
  {
    numeroDepartement: "06",
    nom: "Alpes-Maritimes",
  },
  { numeroDepartement: "07", nom: "Ardèche" },
  { numeroDepartement: "08", nom: "Ardennes" },
  { numeroDepartement: "09", nom: "Ariège" },
  { numeroDepartement: "10", nom: "Aube" },
  { numeroDepartement: "11", nom: "Aude" },
  { numeroDepartement: "12", nom: "Aveyron" },
  {
    numeroDepartement: "13",
    nom: "Bouches-du-Rhône",
  },
  { numeroDepartement: "14", nom: "Calvados" },
  { numeroDepartement: "15", nom: "Cantal" },
  { numeroDepartement: "16", nom: "Charente" },
  {
    numeroDepartement: "17",
    nom: "Charente-Maritime",
  },
  { numeroDepartement: "18", nom: "Cher" },
  { numeroDepartement: "19", nom: "Corrèze" },
  { numeroDepartement: "21", nom: "Côte-d'Or" },
  {
    numeroDepartement: "22",
    nom: "Côtes-d'Armor",
  },
  { numeroDepartement: "23", nom: "Creuse" },
  { numeroDepartement: "24", nom: "Dordogne" },
  { numeroDepartement: "25", nom: "Doubs" },
  { numeroDepartement: "26", nom: "Drôme" },
  { numeroDepartement: "27", nom: "Eure" },
  {
    numeroDepartement: "28",
    nom: "Eure-et-Loir",
  },
  { numeroDepartement: "29", nom: "Finistère" },
  {
    numeroDepartement: "2A",
    nom: "Corse-du-Sud",
  },
  { numeroDepartement: "2B", nom: "Haute-Corse" },
  { numeroDepartement: "30", nom: "Gard" },
  {
    numeroDepartement: "31",
    nom: "Haute-Garonne",
  },
  { numeroDepartement: "32", nom: "Gers" },
  { numeroDepartement: "33", nom: "Gironde" },
  { numeroDepartement: "34", nom: "Hérault" },
  {
    numeroDepartement: "35",
    nom: "Ille-et-Vilaine",
  },
  { numeroDepartement: "36", nom: "Indre" },
  {
    numeroDepartement: "37",
    nom: "Indre-et-Loire",
  },
  { numeroDepartement: "38", nom: "Isère" },
  { numeroDepartement: "39", nom: "Jura" },
  { numeroDepartement: "40", nom: "Landes" },
  {
    numeroDepartement: "41",
    nom: "Loir-et-Cher",
  },
  { numeroDepartement: "42", nom: "Loire" },
  { numeroDepartement: "43", nom: "Haute-Loire" },
  {
    numeroDepartement: "44",
    nom: "Loire-Atlantique",
  },
  { numeroDepartement: "45", nom: "Loiret" },
  { numeroDepartement: "46", nom: "Lot" },
  {
    numeroDepartement: "47",
    nom: "Lot-et-Garonne",
  },
  { numeroDepartement: "48", nom: "Lozère" },
  {
    numeroDepartement: "49",
    nom: "Maine-et-Loire",
  },
  { numeroDepartement: "50", nom: "Manche" },
  { numeroDepartement: "51", nom: "Marne" },
  { numeroDepartement: "52", nom: "Haute-Marne" },
  { numeroDepartement: "53", nom: "Mayenne" },
  {
    numeroDepartement: "54",
    nom: "Meurthe-et-Moselle",
  },
  { numeroDepartement: "55", nom: "Meuse" },
  { numeroDepartement: "56", nom: "Morbihan" },
  { numeroDepartement: "57", nom: "Moselle" },
  { numeroDepartement: "58", nom: "Nièvre" },
  { numeroDepartement: "59", nom: "Nord" },
  { numeroDepartement: "60", nom: "Oise" },
  { numeroDepartement: "61", nom: "Orne" },
  {
    numeroDepartement: "62",
    nom: "Pas-de-Calais",
  },
  {
    numeroDepartement: "63",
    nom: "Puy-de-Dôme",
  },
  {
    numeroDepartement: "64",
    nom: "Pyrénées-Atlantiques",
  },
  {
    numeroDepartement: "65",
    nom: "Hautes-Pyrénées",
  },
  {
    numeroDepartement: "66",
    nom: "Pyrénées-Orientales",
  },
  { numeroDepartement: "67", nom: "Bas-Rhin" },
  { numeroDepartement: "68", nom: "Haut-Rhin" },
  { numeroDepartement: "69", nom: "Rhône" },
  { numeroDepartement: "70", nom: "Haute-Saône" },
  {
    numeroDepartement: "71",
    nom: "Saône-et-Loire",
  },
  { numeroDepartement: "72", nom: "Sarthe" },
  { numeroDepartement: "73", nom: "Savoie" },
  {
    numeroDepartement: "74",
    nom: "Haute-Savoie",
  },
  { numeroDepartement: "75", nom: "Paris" },
  {
    numeroDepartement: "76",
    nom: "Seine-Maritime",
  },
  {
    numeroDepartement: "77",
    nom: "Seine-et-Marne",
  },
  { numeroDepartement: "78", nom: "Yvelines" },
  { numeroDepartement: "79", nom: "Deux-Sèvres" },
  { numeroDepartement: "80", nom: "Somme" },
  { numeroDepartement: "81", nom: "Tarn" },
  {
    numeroDepartement: "82",
    nom: "Tarn-et-Garonne",
  },
  { numeroDepartement: "83", nom: "Var" },
  { numeroDepartement: "84", nom: "Vaucluse" },
  { numeroDepartement: "85", nom: "Vendée" },
  { numeroDepartement: "86", nom: "Vienne" },
  {
    numeroDepartement: "87",
    nom: "Haute-Vienne",
  },
  { numeroDepartement: "88", nom: "Vosges" },
  { numeroDepartement: "89", nom: "Yonne" },
  {
    numeroDepartement: "90",
    nom: "Territoire de Belfort",
  },
  { numeroDepartement: "91", nom: "Essonne" },
  {
    numeroDepartement: "92",
    nom: "Hauts-de-Seine",
  },
  {
    numeroDepartement: "93",
    nom: "Seine-Saint-Denis",
  },
  {
    numeroDepartement: "94",
    nom: "Val-de-Marne",
  },
  {
    numeroDepartement: "95",
    nom: "Val-d'Oise",
  },
  { numeroDepartement: "971", nom: "Guadeloupe" },
  { numeroDepartement: "972", nom: "Martinique" },
  { numeroDepartement: "973", nom: "Guyane" },
  { numeroDepartement: "974", nom: "La Réunion" },
  { numeroDepartement: "976", nom: "Mayotte" },
];
